#!/bin/bash
#This file was created on 02/09/2018
#autoinstaller DWIPANTARA
#coded MR.R3DH3T
#Don't copyright this script bro 

blue='\e[0;34m'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
clear

###################################################
# CTRL C
####################################################
trap ctrl_c INT
ctrl_c () {
clear
echo -e $cyan" Terima Kasih Sudah Memakai Tools DWIPANTARA "
sleep 2
echo ""
echo -e $cyan" Dunia Itu Hanya Sesaat, Jadi Berbuatlah Baik Untuk Akhiratmu "
sleep 2
echo ""
echo -e $cyan" Instagram : dwi_pantara0518 "
sleep 2
echo -e $cyan" Website   : https://dwipantara0518.blogspot.com/ "
sleep 2
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo -e $white" | 1.MsLq | 2.Ksatria Mujahidin | 3.mv24ky | 4.farhan | 5.root-S4D       | "
echo -e $white" | 6.greenhorn | 7.sasman96 | 8.mizuki | 9.nyi_iteung_ | 10.H Code       | "
echo -e $white" | 11.hanum_zaahra | 12.pribumi_jihad | 13.Lokzy | 14.Nc_tesla199        | "
echo -e $white" | 15.Opposite6890 | 16.B0C4HTU4N4K4L | 17.loopstr34k | 18.Emak_Julia    | "
echo -e $white" | 19.pasukan_hitam | 20.Niqabies_women | 21.A | 22._mushab_bin_umair    | "
echo -e $white" | 23.Hidayat | 24.farhan | 25.Dani | 26.rezim_laknat | 27.Squad_monkey3 | "
echo -e $white" | 28.p417ger4n_bers0rb4n | 29.d_dev05 | 30.Mr.Cl4Y | 31.jurnal_jamaah   | "
echo -e $white" +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ "
echo ""
sleep 2
echo -e $cyan" Author MR.R3DH3T : ( follow my Instagram ) @naufalziidane_ "
read enter
exit
}


echo -e $red"   ______        _____ ____   _    _   _ _____  _    ____      _ "
echo -e $red"  |  _ \ \      / /_ _|  _ \ / \  | \ | |_   _|/ \  |  _ \    / \ "
echo -e $red"  | | | \ \ /\ / / | || |_) / _ \ |  \| | | | / _ \ | |_) |  / _ \ "
echo -e $red"  | |_| |\ V  V /  | ||  __/ ___ \| |\  | | |/ ___ \|  _ <  / ___ \ "
echo -e $red"  |____/  \_/\_/  |___|_| /_/   \_\_| \_| |_/_/   \_\_| \_\/_/   \_\ "
echo ""
echo -e $white"        ___ _   _ ____   ___  _   _ _____ ____ ___    _ "
echo -e $white"       |_ _| \ | |  _ \ / _ \| \ | | ____/ ___|_ _|  / \ "
echo -e $white"        | ||  \| | | | | | | |  \| |  _| \___ \| |  / _ \ "
echo -e $white"        | || |\  | |_| | |_| | |\  | |___ ___) | | / ___ \ "
echo -e $white"       |___|_| \_|____/ \___/|_| \_|_____|____/___/_/   \_\ "
echo ""
sleep 2
echo -e $lightgreen"   >> Select Tools For Install << "
echo ""
echo -e $red"   [ 01 ] Metasploit Framework "
echo -e $red"   [ 02 ] Torshammer "
echo -e $red"   [ 03 ] Xerxes " 
echo -e $red"   [ 04 ] SQLmap "
echo -e $red"   [ 05 ] Termux Ohmyzsh for theme "
echo -e $red"   [ 06 ] ko-dork for scann vuln web "
echo -e $red"   [ 07 ] CMS Scamner "
echo -e $red"   [ 08 ] Ngrok "
echo -e $red"   [ 09 ] Webdav "
echo -e $red"   [ 10 ] venom for Backdor "
echo -e $red"   [ 11 ] Shell-Finder "
echo -e $white"   [ 12 ] RED_HAWK "
echo -e $white"   [ 13 ] Kali NetHunter "
echo -e $white"   [ 14 ] hash-generator "
echo -e $white"   [ 15 ] weeman for phising "
echo -e $white"   [ 16 ] Mrcakil "
echo -e $white"   [ 17 ] SpazSms "
echo -e $white"   [ 18 ] Websploit "
echo -e $white"   [ 19 ] Script deface Creator "
echo -e $white"   [ 20 ] fsociety "
echo -e $white"   [ 21 ] Virus "
echo -e $white"   [ 22 ] IPGeolocation " 
echo -e $green"   [ 00 ] Exit "
echo ""
echo -e $white""
read -p " root@dwipantara ~/# " dwipan;

if [ $dwipan = 01 ] || [ $dwipan = 01 ]
then
clear
echo -e $blue" [ Installing Metasploit ] "
sleep 1
apt update && apt upgrade
echo " Harus Sabar! "
sleep 3
pkg install curl
curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
chmod +x metasploit.sh
./metasploit.sh
sleep 5                                                                                               mv metasploit-framework $HOME                                                                         echo " Use msfconsole if you run metasploit "
sleep 2
echo -e $red" { Done Install bro } "
fi


if [ $dwipan = 00 ] || [ $dwipan = 00 ] 
then
clear
echo ">>  Pesan terakhir! << "
echo ""
echo ""
sleep 2
echo -e $white" Jangan pernah tinggalin ngaji karna menuntut ilmu agama itu wajib , suapaya kita tau mana yang salah dan yang benar "
echo ""
sleep 4
echo -e $white" Semangat Berjuang Demi Membela Kebenaran! TAKBIR! " 
echo ""
sleep 4
echo -e $white" Saling memaafkan sesama sodara , wa alfu minkum wassalamu'alaikum warrohmatullohi wabarokatuhu "
fi

if [ $dwipan = 02 ] || [ $dwipan = 02 ]
then 
clear
echo -e $blue" [ Installing Torshammer ] "
apt-get update && apt-get upgrade 
apt-get install git
apt install python 
apt install python2
git clone https://github.com/cyweb/hammer.git
cd hammer
chmod +x hammer.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 03 ] || [ $dwipan = 03 ]
then
clear
echo -e $blue" [ Installing Xerxes ] "
apt-get update && apt-get upgrade -y
apt-get install git -y
apt install clang -y
git clone https://github.com/zanyarjamal/xerxes.git
cd xerxes
clang xerxes.c -o xerxes
echo " use ?  ./xerxes target ( example ) https://www.suaranasional.com 80 "
echo ""
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 04 ] || [ $dwipan = 04 ] 
then
clear
echo -$blue" [ Installing SQLmap-dev ] "
apt-get update && apt-get upgrade
apt-get install git 
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
cd sqlmap-dev
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 05 ] || [ $dwipan = 05 ]
then
clear
echo -e $blue" [ Installing Termux-ohmyzsh ] "
apt-get update && apt-get upgrade
pkg install curl
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
~/.termux/colors.sh
echo -e $white" ganti color ? ketik ~/.termux/colors.sh "
sleep 2
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 06 ] || [ $dwipan = 06 ]
then
clear
echo -e $blue" [ Installing ko-dork ] "
apt-get update && apt-get upgrade
apt-get install git
apt install python
apt install python2
git clone https://github.com/ciku370/ko-dork.git
mv ko-dork $HOME
cd ~/
cd ko-dork
chmod +x *.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 07 ] || [ $dwipan = 07 ]
then
clear
echo -e $blue" [ Installing CMS scanner ] "
apt-get update && apt-get upgrade
pkg install python
apt-get install git
git clone https://github.com/Dionach/CMSmap.git
sleep 1
cd CMSmap
chmod +x cmsmap.py
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 08 ] || [ $dwipan = 08 ]
then
clear
echo -e $blue" [ Installing Ngrok ] "
apt-get update && apt-get upgrade 
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
cd ~/
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 09 ] || [ $dwipan = 09 ] 
then
clear
echo -e $blue" [ Installing Webdav ] "
apt update && apt upgrade
apt install python2
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd ~/
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 10 ] || [ $dwipan = 10 ] 
then
clear
echo -e $blue" [ Installing venom ] "
sleep 2
apt-get install git 
git clone https://github.com/r00t-3xp10it/venom.git
cd venom
sudo chmod -R +x *.sh
sudo chmod -R +x *.py
cd aux
sudo ./setup.sh
echo -e $white" install metasploit dulu bro error kan "
sleep 2
echo ""
echo -e $white" if you run main tools , use msfvenom -h "
sleep 3
echo ""
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 11 ] || [ $dwipan = 11 ]
then
clear
echo -e $blue" [ Installing Shell-finder ] "
apt-get update && apt-get upgrade 
apt-get install git 
apt install python2 
https://github.com/bhavyanshu/Shell-Finder.git
cd Shell-Finder
chmod +x shellfind.py
echo -e $cyan" use python2 if you run main tools bro "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi 

if [ $dwipan = 12 ] || [ $dwipan = 12 ] 
then
clear
echo -e $blue" [ Installing RED_HAWK ] "
sleep 2
apt-get update && apt-get upgrade 
apt get install git 
apt install php
git clone https://github.com/Tuhinshubhra/RED_HAWK
cd RED_HAWK
chmod +x *.php 
echo -e $cyan" if you run main tools , use php "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 13 ] || [ $dwipan = 13 ]
then
clear
echo -e $blue" [ Installing Kali-Nethunter ] "
sleep 2
echo -e $white" Sabar bro sambil ngopi :D "
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 14 ] || [ $dwipan = 14 ] 
then
clear
echo -e $blue" [ Installing hash-generator ] "
apt upgrade && apt update
apt-get install git
apt install python
apt install python2
git clone https://github.com/ciku370/hash-generator
cd hash-generator
chmod +x hashgen.py
sleep 1
echo -e $red" { Done Install bro } "
fi

if [ $dwipan = 15 ] || [ $dwipan = 15 ] 
then
clear
echo -e $blue" [ Installing Weeman ] "
apt-get update && apt-get upgrade 
apt-get install git
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo -e $white" use ngrok bro if you phising your friends "
echo ""
sleep 2
echo -e $red" { Done Install bro } "
fi

