#!/bin/bash
#this file was created on 22/05/2018
#created by MR.R3DH3T
#USE YOUR BRAIN AND SKILL 

green='\e[1;32m'
red='\e[1;31m'
white='\e[1;37m'
yellow='\e[1;33m'
blue='\e[0;34m'

clear
###############################################################
trap ctrl_c INT
ctrl_c() {
clear
echo ""
toilet -F metal -f standard Thanks
echo ""
echo -e $red" >> For Using My Tools :) <<"
echo -e $white"         MR.R3DH3T    "
echo ""
echo -e $white"  >>   instagram : naufalziidane_    "

sleep 1
exit
}
################################################################
echo ""
echo -e $red"                                  WELCOME TO MY TOOLS"
echo ""
echo -e $cyan"    	         >>  Assalamua'alaikum warohmatullohi wabarokatuhu  <<"
echo ""

echo -e $blue "#####################################################################################"
echo -e -n $blue" [X]> USER 		: " $green; whoami
echo -e -n $blue" [X]> TIME 		: " $green; date
echo -e -n $blue" [X]> ACTIVE		: "$green; uptime
echo -e $blue "#####################################################################################"
echo ""
echo -e $white"   [X]> Thanks To : "
echo -e $green" 		    MsLq"
echo -e $green"                    Opposite6890"
echo -e $green"                    Anonymous_greenhorn88"
echo -e $green"                    Loopstr34k"
echo -e $green"                    And all member"
echo -e ""
echo -e $white"   [X]> Greetz    : "
echo -e $green"                    DWIPANTARA "
echo -e $green"                    RAPTOR CODEX"
echo -e $green"                    CYBER MAFIA"
echo -e $green"                    MOSLEM CYBER TEAM"

echo ""
echo ""
echo -e $white"                       __  __      ____  _____ ____  _   _ __________"
echo -e $white"                      |  \/  |_ __|  _ \|___ /|  _ \| | | |___ /_   _|"
echo -e $white"                      | |\/| | '__| |_) | |_ \| | | | |_| | |_ \ | |"
echo -e $white"                      | |  | | | _|  _ < ___) | |_| |  _  |___) || |"
echo -e $white"                      |_|  |_|_|(_)_| \_\____/|____/|_| |_|____/ |_|"
echo -e $red"                     __________________________________________________"
echo -e $red"                     __________________________________________________"
echo ""
echo -e $blue"######################################################################################"
echo ""
################################################################
echo -e $white" #     Select Tools For Install "
echo ""
echo -e $blue"  {01}  RED HAWK"
echo -e $blue"  {02}  Termux Ohmyzsh"
echo -e $blue"  {03}  Ubuntu "
echo -e $blue"  {04}  XAttacker for Termux "
echo -e $blue"  {05}  Weeman "
echo -e $blue"  {06}  PUPPY "
echo -e $blue"  {07}  SQLMAP "
echo -e $blue"  {08}  Metasploit Framework "
echo -e $blue"  {09}  RouterSploit "
echo -e $blue"  {10}  Aircrack-ng "
echo -e $blue"  {11}  IPGeolocation "
echo -e $blue"  {12}  UFONet "
echo -e $blue"  {13}  BruteSploit "
echo -e $blue"  {14}  Venom "
echo -e $blue"  {15}  Facebook-Bruter"
echo -e $blue"  {16}  Admin finder"
echo -e $blue"  {17}  Recondog Information"
echo -e $blue"  {18}  Hammer"
echo -e $blue"  {19}  Katoolin"
echo -e $blue"  {20}  Hydra"
echo -e $blue"  {21}  D-TECT"
echo -e $blue"  {22}  CMSmap"
echo -e $blue"  {23}  Wpscan"
echo -e $blue"  {24}  Magneto add admin exploiter"
echo -e $blue"  {25}  Ngrok"
echo -e $blue"  {26}  viSQL"
echo -e $blue"  {27}  hash-generator"
echo -e $blue"  {28}  GetYou (auto dump)"
echo -e $blue"  {29}  SpazSMS"
echo -e $blue"  {30}  SpamSMS"
echo -e $blue"  {31}  The fat rat"
echo -e $blue"  {32}  Pybelt"
echo -e $blue"  {33}  Websploit"
echo -e $blue"  {34}  Webkiller"
echo -e $blue"  {35}  hasher"
echo -e $blue"  {36}  Mrcakil"
echo -e $blue"  {37}  lscript"
echo -e $blue"  {38}  B4J1N64Nv4"
echo -e $blue"  {39}  PhisingGame"
echo -e $blue"  {40}  ko-dork"
echo -e $blue"  {41}  script deface creator"
echo -e $blue"  {42}  auto download html"
echo -e $blue"  {43}  Virus creator"
echo ""
echo "" 
echo ""
echo -e $white "Type ( Ctrl C ) For Exit"


echo ""
read -p "          root@r3dh3t # " sd;

if [ $sd = 01 ] || [ $sd = 01 ]
then 
clear
echo -e $white" >> Installing RED HAWK << "
echo ""
apt install php
apt install git
git clone https://github.com/Tuhinshubhra/RED_HAWK
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 02 ] || [ $sd = 02 ]
then
clear
echo -e $white" >> Installing termux omyzsh<< "
echo ""
sleep 1
apt-get update && apt-get upgrade
pkg install curl
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
~/.termux/colors.sh
echo -e $red" ganti color ? ketik ~/.termux/colors.sh "
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 03 ] || [ $sd = 03]
then
clear
echo -e $white" >> Installing Ubuntu << "
echo ""
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/r
esolv.conf
echo " Jika di hapus akan ada error "
echo -e $red " >> [Done install brather] << "
fi


if [ $sd = 04 ] || [ $sd = 04 ]
then
clear
echo -e $white" >> Installing XAttacker << "
echo ""
git clone https://github.com/Moham3dRiahi/XAttacker.git
cd XAttacker
chmod +x termux-install.sh
bash termux-install.sh
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 05 ] || [ $sd = 05 ]
then
clear
echo -e $white" >> Installing Weeman << "
echo ""
pkg install pip
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 06 ] || [ $sd = 06 ]
then
clear
echo -e $white" >> Installing PUPPY << "
echo ""
git clone https://github.com/n1nj4sec/pupy.git pupy
cd pupy
git submodule init
git submodule update
pip install -r pupy/requirements.txt
wget https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz
tar xvf payload_templates.txz && mv payload_templates/* pupy/payload_templates/ && rm payload_templates.txz && rm -r payload_templates
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 07 ] || [ $sd = 07 ]
then
clear
echo -e $white" >> Installing SQLMAP << "
echo ""
git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
cd sqlmap-dev
chmod +x *.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 08 ] || [ $sd = 08 ]
then
clear
echo -e $white" >> Installing Metasploit Framework<< "
sleep 1
pkg install curl
curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
chmod +x metasploit.sh
./metasploit.sh
sleep 5
mv metasploit-framework $HOME
echo " Use msfconsole if you run metasploit "
echo -e $red" >> [Done install brather] << " 
fi


if [ $sd = 09 ] || [ $sd = 09 ]
then
clear
echo -e $white" >> Installing RouterSploit<< "
echo ""
apt-get update && upgrade
apt-get install python3-pip
git clone https://www.github.com/threat9/routersploit
cd routersploit
python3 -m pip install -r requirements.txt
python3 rsf.py
cd ..
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 10 ] || [ $sd = 10 ]
then
clear
echo -e $white" >> Installing Aircrack-ng<< "
echo ""
apt-get update && apt-get upgrade
apt-get install aircrack-ng
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 11 ] || [ $sd = 11 ]
then
clear
echo -e $white" >> Installing IPGeolocation<< "
echo ""
apt-get update && apt-get upgrade
apt-get install git
apt install python2
git clone https://github.com/maldevel/IPGeolocation.git
cd IPGeolocaion
chmod +x *.py
pip install -r requirements.txt
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 12 ] || [ $sd = 12 ]
then 
clear
echo -e $white" >> Installing UFONet << "
echo ""
pkg install git
git clone https://github.com/epsylon/ufonet.git
cd ufonet
sudo apt-get install python-pycurl python-geoip python-whois python-crypto python-requests
pip install geoip
pip install requests
pip install pycrypto
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 13 ] || [ $sd = 13 ]
then 
clear
echo -e $white" >> Installing BruteSploit << "
echo ""
git clone https://github.com/Screetsec/Brutesploit.git
cd Brutesploit
chmod +x Brutesploit
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 14 ] || [ $sd = 14 ]
then 
clear
echo -e $white" >> Installing Venom << "
echo ""
git clone https://github.com/r00t-3xp10it/venom.git
cd venom
sudo chmod -R +x *.sh
sudo chmod -R +x *.py
cd aux
sudo ./setup.sh
echo ""
echo -e $red" >> [Done install brather] << ""run main tools >> msfvenom <<"
echo -e $white" kalo mau jalanin venom install metasploit dulu bro "
fi


if [ $sd = 15 ] || [ $sd = 15 ]
then 
clear
echo -e $white" >> Installing Facebook-Bruter << "
echo ""
apt-get update && apt-get upgrade
git clone https://github.com/imadoxhunter/Facebook-Bruter.git
echo -e $red" >> [Done install brather] << "
fi
if [ $sd = 16 ] || [ $sd = 16 ]
then 
clear
echo -e $white" >> Installing admin finder << "
echo ""
apt install python
apt install python2
chmod +x r3dh3t.py
python2 r3dh3t.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 17 ] || [ $sd = 17 ]
then 
clear
echo -e $white" >> Installing Recondog Inforamation << "
echo ""
apt install python
apt install python2
chmod +x dog.py
python2 dog.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 18 ] || [ $sd = 18 ]
then 
clear
echo -e $white" >> Installing Hammer << "
echo ""
apt-get update && apt-get upgrade
pkg install python
git clone https://github.com/cyweb/hammer.git
cd hammer
chmod +x hammer.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 19 ] || [ $sd = 19 ]
then 
clear
echo -e $white" >> Installing Katoolin << "
echo ""
apt update && apt upgrade
pkg install git
pkg install python2
pkg install gnupg
pkg install nano
git clone https://github.com/LionSec/katoolin.git
cd ~/katoolin
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 20 ] || [ $sd = 20 ]
then 
clear
echo -e $white" >> Installing Hydra << "
echo ""
apt update && apt install -y wget
apt install hydra
wget http://scrapmaker.com/download/data/wordlists/dictionaries/rockyou.txt
cd ~/
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 21 ] || [ $sd = 21 ]
then 
clear
echo -e $white" >> Installing D-TECT << "
echo ""
git clone https://github.com/shawarkhanethicalhacker/D-TECT.git
cd D-TECT
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 22 ] || [ $sd = 22 ]
then
clear
echo -e $white " >> Installing CMSmap << "
echo ""
pkg install git
apt install python -y
apt install python2 -y
git clone https://github.com/Dionach/CMSmap.git
cd CMSmap
chmod +x cmsmap.py
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 23 ] || [ $sd = 23 ]
then
clear
echo -e $white " >> Installing Wpscan << "
echo ""
apt-get update && apt-get upgrade
apt install ruby
apt install curl
git clone git clone https://github.com/wpscanteam/wpscan
cd ~/wpscan
gem install bundle
bundle config build.nokogiri --use-system-libraries
bundle install
ruby wpscan.rb --update
echo ""
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 24 ] || [ $sd = 24 ] 
then
clear
echo ""
echo -e $white " >> Installing Magneto add admin exploiter << "
apt-get install php
mkdir magneto
cd ~/magneto
wget https://pastebin.com/raw/PXkG73pG -O magento.php
echo ""
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 25 ] || [ $sd = 25 ]
then
clear
echo -e $white " >> Installing Ngrok << "
echo ""
apt-get update
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
echo ""
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 26 ] || [ $sd = 26 ]
then
clear
echo -e $white " >> Installing viSQL << "
echo ""
apt-get update 
pkg install git
pkg install python2 
git clone https://github.com/blackvkng/viSQL.git
cd ~/ viSQL
chmod 777 viSQL.py
echo ""
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 27 ] || [ $sd = 27 ]
then
clear
echo -e $white " >> Install hash-generator << "
echo ""
apt upgrade && apt update
pkg install git
apt install python
apt install python2
git clone https://github.com/ciku370/hash-generator
cd hash-generator
chmod +x hashgen.py
sleep 2
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 28 ] || [ $sd = 28 ]
then
clear
echo -e $white " >> Installing GetYou << "
echo ""
pkg install git 
apt install python
git clone https://github.com/M413-M/GetYou.git
cd GetYou
chmod +x getyou
echo " Usage ? ./getyou "
sleep 4
echo -e $red" >> [Done install brather] << " 
fi


if [ $sd = 29 ] || [ $sd = 29 ]
then
clear
echo -e $white " >> Installing SpazSMS << "
echo ""
pkg install git
apt install python
apt install php
git clone https://github.com/Gameye98/SpazSMS.git
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 30 ] || [ $sd = 30 ]
then
clear
echo -e $white " >> Installing SpamSMS << "
echo ""
pkg install git
pkg install php
pkg install python
pkg install curl
git clone https://github.com/Senitopeng/SpamSms.git
echo ""
echo -e $red" >> [Done install brather] << " "USAGE CAll All  nano no.txt"
fi


if [ $sd = 31 ] || [ $sd = 31 ]
then
clear
echo -e $white" >> instLling TheFatRat << "
echo ""
apt-get update && upgrade
pkg install python
pkg install git
git clone https://github.com/Screetsec/TheFatRat.git
cd TheFatRat
chmod +x setup.sh && ./setup.sh
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 32 ] || [ $sd = 32 ] 
then
clear
echo -e $white" >> installing Pybelt << "
echo ""
apt-get update && apt-get upgrade
pkg install python && python2
pkg install git
git clone https://github.com/Ekultek/Pybelt.git
cd Pybelt
pip install -r requirements.txt
chmod +x pybelt.py
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 33 ] || [ $sd = 33 ]
then
clear
echo -e $white" >> isntalling websploit << "
echo ""
apt-get update && apt-get upgrade
pkg install git
pkg install python2
git clone https://github.com/The404Hacking/websploit.git
cd websploit
chmod +x websploit
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 34 ] || [ $sd = 34 ]
then
clear
echo -e $white" >> installing webkiller << "
echo ""
apt-get update && apt-get upgrade
pkg install git
pkg install python
git clone git clone https://github.com/ultrasecurity/webkiller.git
cd webkiller
pip install -r requirements.txt
chmod +x webkiller.py
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 35 ] || [ $sd = 35 ]
then
clear
echo -e $white" >> install hasher << "
echo ""
apt update && apt upgrade
apt install git
apt install python
apt install python2
git clone https://github.com/CiKu370/hasher.git
mv hasher $HOME
cd ~/
cd hasher
chmod +x hash.py 
python2 hash.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 36 ] || [ $sd = 36 ] 
then
clear
echo -e $white" >> installing Mrcakil << "
echo ""
pkg install git
git clone https://github.com/mrcakil/Mrcakil.git
mv Mrcakil $HOME
cd Mrcakil
chmod +x tools
chmod +x tools2
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 37 ] || [ $sd = 37 ]
then
clear
echo -e $white" >> installing lscript << "
echo ""
apt-get update && atp-get upgrade
pkg install git 
git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x .sh
./install.sh
echo -e $red" >> [Done install brather] << "
fi

if [ $sd = 38 ] || [ $sd = 38 ]
then
clear
echo -e $white" >> intalling B4J1N64Nv4 << "
echo ""
pkg install python
pkg intsall git
git clone https://github.com/DarknessCyberTeam/B4J1N64Nv4.git
mv B4J1N64Nv4 $HOME
cd B4J1N64Nv4
chmod +x bajingan.sh
echo ""
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 39 ] || [ $sd = 39 ]
then
clear
echo -e $white" >> Installing PhisingGame << "
pkg update && upgrade 
pkg install git
pkg install python2
git clone https://github.com/senitopeng/PhisingGame.git
cd PhisingGame
chmod +x .py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 40 ] || [ $sd = 40 ]
then
clear
echo -e $white" >> Installing ko-dork << "
echo ""
pkg update && upgrade 
pkg install git
pkg install python
pkg install python2
git clone https://github.com/ciku370/ko-dork.git
mv ko-dork $HOME
cd ~/
cd ko-dork
chmod +x *.py
echo -e $red" >> [Done install brather] << "
fi


if [ $sd = 41 ] || [ $sd = 41 ]
then
clear
echo -e $white" >> Installing script deface creator << "
echo ""
apt update && apt upgrade
apt install python
apt install python2
chmod +x dwipan.py
python2 dwipan.py
echo -e $red" >> [Done install brather] << "
fi 


if [ $sd =42 ] || [ $sd = 42 ]
then
clear
echo -e $white" >> Installing Dhtml << "
apt install python2
chmod +x *.py
python2 Dhtml.py
echo -e $red" >> [Done install brather] <<"
fi

if [ $sd = 43 ] || [ $sd = 43 ]
then
clear
echo -e $white" >> Installing Vbug << "
apt update && apt upgrade
apt install python
apt install python2
unzip vbug.zip
cd vbug
chmod +x *.py
ls
echo " Use python2 bro "
echo -e $red" >> [Done install brather] << "
fi
